.gitignore
docs/reference.rst

Done primarily to fix a syntax error, but also normalized usage of all `:meth:`.

Fix :meth: usage

---

docs/reference.rst

When you use `.. class::` it  will automatically add `class` to the output. Putting `.. class:: class` prevents automatic linking of `:cls:`.

Fix class directives

---

docs/tutorial.rst

Try/Except indentation didn't match in the code snippet

Fix indentation in tutorial code example

---

.gitignore
curio/test/subprocess.py

Allows to start test with python3.5 if python3 default is set to another version.

Fix Python executable in test, use sys.executable instead of hard coded string.

---

.travis.yml
curio/task.py
docs/devel.rst
docs/index.rst
docs/reference.rst
docs/tutorial.rst
pytest.ini
setup.py

Proof of concept. Anyone want to take it from here?
ref: #57

have pytest run code examples in docs + have travis build docs

---

README.rst
examples/hello.py

As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.

Convert readthedocs links for their .org -> .io migration for hosted projects

---

curio/kernel.py

I noticed that after running `curio.run()` a KQUEUE file descriptor would be held open by the Python process (I'm on OS X), effectively leaking them with multiple runs. I tracked it down to the `Kernel._selector` not being closed when shutting down.
Here's a terminal session illustrating the issue with lsof:
```
$ cat curio_shutdown.py 
import curio
curio.run(curio.sleep(1))
curio.run(curio.sleep(1000))
$ python3 curio_shutdown.py &
[1] 71835
$ lsof -p 71835 | grep KQUEUE
Python  71835 sterling    4u  KQUEUE                           count=0, state=0x8
Python  71835 sterling    5u  KQUEUE                           count=0, state=0x8
$ kill %1
[1]+  Terminated: 15          python3 curio_shutdown.py
$ 
$ # after applying fix
$ 
$ python3 curio_shutdown.py &
[1] 71851
$ lsof -p 71851 | grep …
```

Close selector when shutting down resources

---

.travis.yml
docs/reference.rst

This fixes all warnings when building the docs, hence making all future docs warnings an error under Travis.
Closes #34

Fix references in the docs

---

examples/conn.py
examples/echoserv.py
examples/echoserv2.py
examples/echoserv3.py
examples/echoserv4.py
examples/echoserv5.py
examples/fibserve.py
examples/hello.py
examples/pinger.py
examples/prodcons.py
examples/ssl_echo.py
examples/ssl_echo_client.py
examples/ssl_http.py
examples/udp_echo.py
examples/udp_echo_client.py
examples/unix_echo.py
examples/unix_echo_client.py

Please excuse the unsolicited pull request. I understand that this is a personal preference and I will totally understand if the pull request is denied.
Catch KeyboardInterrupt to not make the user think an error occurred when killing the server with CTRL+c
Make SSL cert and key file locations absolute paths to be able to run the example from a different directory

Make the examples a little more accessible

---

curio/__init__.py
curio/kernel.py
curio/task.py
curio/tls.py
docs/reference.rst
docs/tutorial.rst
tests/test_tls.py

Implement task-local storage for curio.
No tests yet, but everything else is there.
I added a nice example of the API in action to the tutorial -- probably that's the thing to look at first.
To highlight the two API decisions that are most likely to be controversial / I'm most uncertain about:
I made the interface totally usable from synchronous code. Aside from being weird, this does force certain decisions in the implementation -- in particular it requires some hoop-jumping to set up and maintain a global (thread-local) rendesvous point for locating the current task metadata. This might have performance implications -- I haven't run benchmarks. (Specifically, doing it this way means there's a bit of extra overhead at every task switch; on the other hand, I suspect but haven't checked …

Task-local storage

---

curio/sync.py
docs/reference.rst
tests/test_sync.py

This PR introduced the RLock implementation, similar to the `threading.RLock`.
This enables curio to allow users to re-acquire the lock if it is own by the 
same `curio.Task` instance. Here is an example use case:
``` python
import curio
async def coro(lck):
async with lock:
print('Critical section')
async def parent_coro(lck):
async with lock:
await coro()
async def main():
await curio.spawn(parent_coro(curio.RLock()))
if __name__ == '__main__':
curio.run(man())
```
If the above code was using a simple `curio.Lock`, it would end up in a deadlock, while with
a reentrant lock it works just fine.

Implement reentrant lock

---

curio/kernel.py
curio/task.py
curio/traps.py
tests/test_kernel.py

curio.defer_cancellation is an async context manager which defers any
cancellations until after leaving the 'async with' block. See
gh-96.
It *should* also defer timeout exceptions, but it doesn't yet.
cancel_no_wait is like cancel, but it doesn't wait for the task to
exit. I needed it to write a test for defer_cancellation, and was just
wanting it anyway for some user code I was working on...
I'm not sure whether it makes sense to have both cancel() and
cancel_no_wait() -- maybe cancel_no_wait() should be renamed to just
become cancel()? But for now I left both in.

Add curio.defer_cancellation and Task.cancel_no_wait

---

curio/kernel.py
curio/traps.py
docs/reference.rst
tests/test_kernel.py

Refactor trap internals to formalize the distinction between regular and "synchronous" traps. See #101 for motivation. Also convert the "obvious" traps to make them sync traps.
Specifically, the following traps are made sync:
* `adjust_cancel_defer_depth`
* `get_kernel`
* `get_current`
* `set_timeout`
* `unset_timeout`
* `queue_reschedule_function`
* `clock`
* `sigwatch`
* `sigunwatch`
The following traps in principle *could* be made sync, but either there's some complication or it isn't obvious whether those are actually the semantics we want, so I left them alone for now:
* `cancel_task`
* `spawn`
* `reschedule_tasks`
When switching traps to make them synchronous I also renamed them. This isn't at all mandatory, but since the name of the trap = the name of the trap handler function, and …

Sync traps

---

curio/kernel.py
curio/monitor.py

In this PR:
- enhanced the CLI for curio.monitor using `argparse`
- properly terminate the monitor thread when exiting from the kernel

Improve the monitor CLI and internals

---

curio/kernel.py
curio/task.py
curio/traps.py
docs/reference.rst
tests/test_kernel.py
tests/test_queue.py
tests/test_socket.py
tests/test_sync.py

This implements the ideas described in gh-101, esp.
https://github.com/dabeaz/curio/issues/101#issuecomment-261477568
Specifically, it makes it so all traps are either "blocking" or
"synchronous", where those have consistent, well-defined meaning:
blocking traps trigger scheduling, are cancellation points, and are
timeout points; sync traps do none of those things. The trap handler
calling conventions in the kernel are adjusted to follow this.
Branch also contains some logically independent cleanups that fit in
with the changes I was making anyway:
- Cleaned up cancellation logic so that it no longer requires the
cancelling task to race with the victim task.
- defer_cancellation now defers timeouts as well as cancel calls.
- Renamed Task.cancel_no_wait to Task.cancel(blocking=False)

[rfc] Finish splitting traps into blocking vs. synchronous

---

curio/kernel.py
curio/task.py
curio/traps.py
docs/reference.rst
tests/test_kernel.py
tests/test_queue.py
tests/test_socket.py
tests/test_sync.py

[Note that this is based off the blocking traps branch, #116. There's
only 1 new commit here beyond that. Github's UI will probably make this
look confusing; going into the individual changes view will help.]
allow_cancellation is the inverse of defer_cancellation. The innermost
block wins.
Example code where this is useful -- implementing a task supervisor:
```python
async def run(self, initial_coros):
self._started = True
chained_exc = None
async with curio.defer_cancellation:
for coro in initial_coros:
await self.spawn(coro)
while self._tasks or not self._shutting_down:
try:
async with curio.allow_cancellation:
task = await self._q.get()
self._process_finished_task(task)
except BaseException as exc:
if not self._shutting_down:
await self.shutdown()
if chained_exc is not None: …
```

Add 'async with allow_cancellation'

---

curio/kernel.py

I can't even figure out how the tests managed to pass before...

Fix a foolish bug in _check_pending_cancellation

---

curio/kernel.py
tests/test_kernel.py

This is well-defined and easy to do with the new cancellation
implementation: the task just gets marked as being cancelled, and then
the next time it executes a blocking trap, the CancelledError is
raised.
Okay, so we *can* do it. But is it useful? Actually, yes. Here's the
situation where I ran into this: I have a "supervisor" whose job it is
to manage a set of child tasks. One of the operations the supervisor
exposes is a `shutdown` method, which tells the supervisor to stop
accepting new tasks and cancels all extant tasks. I tried having one
of the tasks that runs *inside* the supervisor call `shutdown`. This
is a perfectly sensible thing it do -- in fact, the whole idea here is
that you make the supervisor task the "main" task, and then run *all*
your code as sub-tasks under it. And …

Allow tasks to cancel themselves

---

curio/local.py
tests/test_local.py

- use ```__slots__``` to decrease a memory footprint of ```curio.Local```
- ```vars()``` and ```dir()``` now work correctly when used with ```Local```
- forbid using ```Local``` outside of asynchronous context

Improve task locals API

---

curio/sync.py
docs/reference.rst
tests/test_sync.py

The kwarg is named `reserve_thread` not `reserve`, so use
`reserve_thread` consistently everywhere.

Fix the name of a kwarg to the `abide` function

---

curio/local.py
tests/test_local.py

When managing task-local storage, make sure the task-local storage is
connected to the current executing thread, allowing the creation of
multiple curio kernels, one-per-thread.

make curio.local thread-safe

---

curio/kernel.py

Previous attempts to solve #75 included moving _init_loopback_task outside the main run() loop.
This fails to solve the problem because new tasks are simply added to the *ready* queue and that is not processed until the selector is called to look for new events.
This fixes #75 by moving the selector code and subsequent processing of events to the end of the run loop.
It does indeed solve the problem on windows, so far without an increase in stinging bat density.
It should be noted I'm quite out of my depth at this point, so proceed with caution!

Don't try and select until after ready events have been processed

---

curio/network.py

If the `ssl=` argument passed to `curio.network._wrap_ssl_client()` is not a bool but
an `ssl.SSLContext` or equivalent, the returned wrapped socket is now
wrapped in a curio `Socket` so that it (a) is made non-blocking and
(b) has an awaitable `do_handshake()` method.

Improved wrapping of sockets.

---

curio/kernel.py
tests/test_kernel.py

[Reference](https://github.com/dabeaz/curio/blob/master/docs/reference.rst) specifies that `Kernel.run()` should "run the coroutine
*coro* to completion and return its final return value."

Make Kernel.run() return coroutine's return value

---

examples/ws_server.py

Hi!
Keep in mind I have Python async-y experience (I wrote aiofiles and pytest-asyncio) but I'm a Curio novice.
This is what I've been playing with. The websocket protocol implementation is from https://github.com/jeamland/wsproto. Wsproto is written in the sans-io style, i.e. the protocol logic but without any I/O. This is super for us, since we can just glue this to Curio easily.
I guess my idea was to expect users to implement handlers using two queues. There's an in queue, where you get stuff sent by a client, and an out queue where you put stuff to send to the client.
So this is what a user might write (as seen below in the code):
```
async def ws_echo_server(in_queue, out_queue):
"""Just echo websocket messages, reversed. Echo 3 times, then close."""
for _ in range(3):
msg = await …
```

Websocket example.

---

curio/__init__.py
curio/bridge.py
curio/kernel.py

This allows you to run asyncio coroutines from within curio, using a new function `curio.acb` (Asyncio Curio Bridge). 
I put this inside the kernel because it's the easiest and most user-friendly way of co-operating the two event loop types.
The `asyncio` event loop runs inside a thread that is booted when `curio.run()` starts, and stops when it exits. asyncio coroutines are submitted to the worker event loop via `run_coroutine_threadsafe` and the resulting future is then awaited on. 
Right now, there's no additional tests or documentation.

Add basic curio -> asyncio coroutine bridge.

---

curio/meta.py
tests/test_asyncgen.py
tests/test_meta.py

This fix issue: #217
Add support for Python3.6 asynchronous generator function in curio.meta.iscoroutinefunction function.

add python3.6 asynchronous generator function support for AsyncABC

---

curio/bridge.py
tests/test_asyncio.py

This adds some improvements to the asyncio bridge, such as:
- A decorator that allows easier `await`ing of foreign coroutines
- The ability to pass keyword arguments to a corofunc
- The ability to pass a coroutine object straight into the loop.
The first one was my main use case for one of my projects; it's easier than running the loop manually every time.

asyncio bridge improvements

---

curio/monitor.py

This adds a sleep column to the monitor, which will show sleep times for any sleeping tasks.
```
curio > ps      
Task   State        Cycles     Timeout Sleep   Task                                               
------ ------------ ---------- ------- ------- --------------------------------------------------
1      FUTURE_WAIT  1          None    None    Monitor.monitor_task                              
2      READ_WAIT    1          None    None    Kernel._run_coro.<locals>._kernel_task            
3      TIME_SLEEP   1          None    5996.34 testfn  
```
The alternative way is to have this read in the timeout column, but I figured that might be confusing.

Add sleep readout to monitor

---

examples/curio_zmq.py

pyzmq no longer ships nor needs its own selector.  This breaks some of the examples provided with curio.  However, the fix is easy: remove everything that relies on ZMQSelector.
This probably makes integration with other types of sockets easier (or even possible).

fix zmq example for version 17.0.0+

---

docs/reference.rst

Without joining those tasks the program runs much
faster than expected by novice users.
This change makes  the example work as expected.
I also added more verbose text output,
showing state of the semaphore.

add join for tasks in semaphore example

---

docs/devel.rst

This is how the example should run:
```
>>> run(main)
T-minus 5
T-minus 4
T-minus 3
T-minus 2
T-minus 1
```
Prior to this fix, it stops at 2:
```
>>> run(main)
T-minus 5
T-minus 4
T-minus 3
T-minus 2
```

Fix AsyncCountdownIter example in docs/devel.rst

---

README.rst
tests/conftest.py
tests/test_file.py
tests/test_io.py
tests/test_socket.py

Two main changes:
1. use a pytest fixture tmpdir for writing to a file ephemerally
2. write a portno fixture to get an 'almost' unique port no

Make tests work with pytest-xdist (partial #264)

---

curio/queue.py

This patch removes the call with asyncio.wait_for in the asyncio versions of UniversalQueue.put and get. Since Asyncio can directly await wrapped futures. Using asyncio.wait_for with a timeout of zero does nothing.
Closes #267

Wait for wrapped futures directly in get and put

---

docs/reference.rst

There is no `curio.abc` module. Import from correct modules instead.

Fix imports in AsyncABC example

---

curio/workers.py

Hey David (@dabeaz), a one-liner fix to `spawn` because process pool workers are expected to be "clean" interpreters as you mention [here](https://github.com/dabeaz/curio/issues/165#issuecomment-385264390). We were getting unexpected behaviour with the current version using `fork` because the new processes would have Curio kernel running (curio.meta.curio_running() was True). Test suite seems to pass as before. Thanks!

fork to spawn

---

.travis.yml

Hey,
I modified the Travis configuration slightly to also run the test suite on Windows. As you can see after merging this, some of the tests currently fail on Windows (they do on Travis and on my computer).
I'm not sure if the project officially supports Windows - the documentation doesn't mention anything about that as far as I can see. If it's not supported, just close this PR and maybe mention that somewhere. Otherwise I think it would be a good idea to have an overview of how the tests behave on Windows.
Let me know if you would rather have the Windows build as "allowed failure" so it doesn't cause the entire job to fail.

Travis: Run tests on Windows too

---

.gitignore
curio/pytest_plugin.py
setup.py

If you write an app using Curio, you'll want to do unit tests. If you use pytest then this change adds a pytest plugin that can be used for that. If you install Curio, you automatically get the pytest plugin for Curio, so users don't have to install another package to do their own unit tests.

Add built-in pytest plugin. Enables easier unit tests of Curio apps.

---

curio/pytest_plugin.py

Here it is:
```
.venv/lib/python3.7/site-packages/curio/pytest_plugin.py:60
.venv/lib/python3.7/site-packages/curio/pytest_plugin.py:60
/Users/sobolev/Documents/github/returns/.venv/lib/python3.7/site-packages/curio/pytest_plugin.py:60: PytestDeprecationWarning: direct construction of Function has been deprecated, please use Function.from_parent
item = pytest.Function(name, parent=collector)
-- Docs: https://docs.pytest.org/en/latest/warnings.html
```
I am not sure that it will work, let's find out!

Address pytest deprecation warning

---

curio/pytest_plugin.py
tests/test_pytest_plugin.py

Using "keywords" here conflicts with the AnyIO pytest plugin.
Fixes #327.

Fixed pytest plugin wrapping functions too eagerly

---

tests/test_io.py
tests/test_network.py
tests/test_socket.py

Commit fixing the following issue:
```
E       AssertionError: assert ['client start',\n 'handler start',\n 'recv wait',\n ('handler', b'Msg1'),\n 'recv wait',\n ('client', b'Msg1'),\n ('handler', b'Msg2'),\n 'recv wait',\n ('client', b'Msg2'),\n 'client close'] == ['client start',\n 'handler start',\n 'recv wait',\n ('handler', b'Msg1'),\n 'recv wait',\n ('client', b'Msg1'),\n ('handler', b'Msg2'),\n 'recv wait',\n ('client', b'Msg2'),\n 'client close',\n 'handler done']
E         Right contains one more item: 'handler done'
E         Full diff:
E           [
E            'client start',
E            'handler start',
E            'recv wait',
E            ('handler',
E             b'Msg1'),
E            'recv wait',
E            ('client',
E             b'Msg1'),
E            ('handler', …
```

Add missing sleep after sock.close() in tcp echo tests

---

curio/kernel.py

python3.10 sets e.errno to 22 instead of 10022 so we need to check against both WSAEINVAL and EINVAL

Fix for windows OSError raised when select is called with empty lists since python 3.10.5
